# config/packages/security.yaml
security:
    providers:
        in_memory:
          memory:
            users:
                visitor:
                    password: visitor
                    roles: 'ROLE_USER'
                admin:
                    password: password
                    roles: 'ROLE_ADMIN'
    encoders:
            Symfony\Component\Security\Core\User\User: plaintext
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
          anonymous: ~
          http_basic: ~
    access_control:
      - { path: ^/admin, roles: ROLE_ADMIN }

