# config/packages/security.yaml
security:
    providers:
        in_memory:
          memory:
        our_db_provider:
          entity:
            class: App\Entity\User
            property: username
    encoders:
      App\Entity\User:
                  algorithm: bcrypt
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
          anonymous: ~
          provider: our_db_provider
          form_login:
            login_path: admin_login
            check_path: admin_login
            default_target_path: admin_home
          logout:
            path:   logout
            target: admin_login
            invalidate_session: true
    access_control:
      - { path: ^/admin, roles: ROLE_ADMIN }

